.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
import
*.csv
*.sql

apps/*
!apps/backend
!apps/backend/**
!libs
!libs/event-manager-m2m-contracts
!libs/event-manager-m2m-contracts/**
!libs/shared-data-types
!libs/shared-data-types/**
!libs/shared-utils
!libs/shared-utils/**
!certificate-templates
!certificate-templates/**
