.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
import
*.csv
*.sql

apps/*
!apps/backend
!apps/backend/**
!libs
!libs/**
!certificate-templates
!certificate-templates/**
