-- AlterEnum
ALTER TYPE "AuditLogEntityType" ADD VALUE IF NOT EXISTS 'EVENT_FORM' AFTER 'EVENT_LECTURER';
ALTER TYPE "AuditLogEntityType" ADD VALUE IF NOT EXISTS 'EVENT_FORM_LINK' AFTER 'EVENT_FORM';
ALTER TYPE "AuditLogEntityType" ADD VALUE IF NOT EXISTS 'EVENT_FORM_RESPONSE' AFTER 'EVENT_FORM_LINK';
