import { InjectionToken, reflectComponentType } from '@angular/core';
import { moduleMetadata, type Decorator } from '@storybook/angular';

const STORYBOOK_SCENARIO = new InjectionToken<string>('Storybook scenario');

/**
 * Recreate a data-driven story when its scenario controls change.
 *
 * Angular Storybook updates component inputs in place, but does not replace
 * applicationConfig providers. Pages that load data during construction need a
 * fresh injector to consume the new route, service, or MSW scenario. Use this
 * decorator only for those stories; ordinary input controls need no remount.
 * Scenario args are not component properties: a control named like an internal
 * signal must never replace that signal. Only real inputs/outputs are forwarded
 * by default; a custom render template owns its explicit props mapping.
 */
export function withScenarioControls<TArgs>(): Decorator<TArgs> {
  return (story, context) => {
    const result = story();
    const component = context.component ? reflectComponentType(context.component) : null;
    const sourceProps: Record<string, unknown> = Object.assign({}, context.args, result.props);
    // Angular prepares an autogenerated template before running decorators.
    // Its presence alone does not mean the author supplied a props mapping.
    const bindings = [...component?.inputs ?? [], ...component?.outputs ?? []];
    const props: Record<string, unknown> = result.userDefinedTemplate ? result.props ?? {} : Object.fromEntries(
      bindings
        .filter((binding) => binding.templateName in sourceProps || binding.propName in sourceProps)
        .map((binding) => [binding.templateName, binding.templateName in sourceProps
          ? sourceProps[binding.templateName]
          : sourceProps[binding.propName]]),
    );
    let template = result.template;
    if (!result.userDefinedTemplate && component) {
      const inputs = component.inputs.filter((input) => input.templateName in props).map((input) =>
        `[${input.templateName}]="this['${input.templateName}']"`,
      );
      const outputs = component.outputs.filter((output) => typeof props[output.templateName] === 'function').map((output) =>
        `(${output.templateName})="this['${output.templateName}']($event)"`,
      );
      template = `<${component.selector} ${[...inputs, ...outputs].join(' ')}></${component.selector}>`;
    }

    return moduleMetadata({
      providers: [{
        provide: STORYBOOK_SCENARIO,
        useValue: JSON.stringify({
          args: context.args,
          network: context.globals['network'],
          serviceWorker: context.globals['serviceWorker'],
        }),
      }],
    })(() => ({ ...result, props, template, userDefinedTemplate: true }), context);
  };
}
