.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
import
certificate-templates
*.csv
*.sql

apps/*
!apps/admin
!apps/admin/**
!libs
!libs/**
