export function createPublicMajorEventRecord(overrides: Record<string, unknown> = {}) {
  return {
    id: 'major-1',
    name: 'Major 1',
    emoji: null,
    startDate: new Date('2026-06-24T12:00:00.000Z'),
    endDate: new Date('2026-06-25T12:00:00.000Z'),
    description: null,
    buttonText: null,
    buttonLink: null,
    contactInfo: null,
    contactType: null,
    subscriptionStartDate: null,
    subscriptionEndDate: null,
    maxCoursesPerAttendee: null,
    maxLecturesPerAttendee: null,
    maxUncategorizedPerAttendee: null,
    rankedSubscriptionEnabled: false,
    isPaymentRequired: false,
    additionalPaymentInfo: null,
    certificateConfigs: [],
    majorEventPrices: [],
    ...overrides,
  };
}

export function createPublicEventRecord(overrides: Record<string, unknown> = {}) {
  return {
    id: 'event-1',
    name: 'Evento público',
    creditMinutes: 120,
    startDate: new Date('2026-06-24T12:00:00.000Z'),
    endDate: new Date('2026-06-24T14:00:00.000Z'),
    emoji: null,
    type: 'MINICURSO',
    description: null,
    shortDescription: null,
    latitude: null,
    longitude: null,
    locationDescription: null,
    majorEventId: null,
    majorEvent: null,
    eventGroupId: null,
    eventGroup: null,
    allowSubscription: true,
    subscriptionStartDate: null,
    subscriptionEndDate: null,
    slots: null,
    slotsAvailable: null,
    queueCount: 0,
    autoSubscribe: false,
    shouldIssueCertificate: true,
    shouldIssueCertificateForNonPayingAttendees: false,
    shouldIssueCertificateForNonSubscribedAttendees: false,
    shouldCollectAttendance: true,
    isOnlineAttendanceAllowed: false,
    onlineAttendanceStartDate: null,
    onlineAttendanceEndDate: null,
    publiclyVisible: true,
    youtubeCode: null,
    buttonText: null,
    buttonLink: null,
    lecturers: [],
    ...overrides,
  };
}
