import { FormBuilder, Validators } from '@angular/forms';
import { livestreamValidator, placementPointsValidator } from './sports-workspace-form.utils';

export function createSportsWorkspaceForms(fb: FormBuilder) {
  const overallPlacementPoints = fb.array([createPlacementPointForm(fb, 1)], placementPointsValidator);
  overallPlacementPoints.clear();
  return {
    tournament: fb.nonNullable.group({
      status: ['DRAFT'],
      scoringMode: ['PER_SPORT'],
      selfSubscriptionEnabled: [false],
      selfSubscriptionAllowNoTeam: [false],
      selfSubscriptionAllowNoCategory: [false],
      allowPlayerMultipleTeams: [false],
    }),
    category: fb.nonNullable.group({
      id: [''],
      name: ['', Validators.required],
      emoji: ['⚽', Validators.required],
      sport: ['SOCCER'],
      customSportName: [''],
      division: [''],
      format: ['SINGLE_ELIMINATION'],
      status: ['DRAFT'],
      registrationStartDate: [''],
      registrationEndDate: [''],
      minimumRosterSize: [0],
      maximumRosterSize: [0],
      maximumCaptains: [0],
      maximumCoaches: [0],
      allowPlayerMultipleTeams: [false],
      periodsEnabled: [false],
      maximumPeriods: [0],
      periodLabel: ['Tempo'],
      timerPreset: ['SOCCER'],
      timerOverallEnabled: [true],
      timerPeriodEnabled: [true],
      timerPeriodDurationMinutes: [45, [Validators.min(0), Validators.max(1440)]],
      timerAllowOvertime: [true],
      timerPeriodStartOffsetsMinutes: ['0, 45', Validators.pattern(/^\s*\d+(?:\.\d+)?(?:\s*,\s*\d+(?:\.\d+)?)*\s*$/)],
      rulesText: [''],
      scoreRulesJson: ['{}'],
      scoreAllowDraw: [true],
      scoreHigherWins: [true],
      scorePointStep: [1, [Validators.required, Validators.min(0.000001)]],
      overallScoringMode: ['NONE'],
      overallMatchWinPoints: [3, [Validators.min(0), Validators.max(1_000_000)]],
      overallMatchDrawPoints: [1, [Validators.min(0), Validators.max(1_000_000)]],
      overallMatchLossPoints: [0, [Validators.min(0), Validators.max(1_000_000)]],
      overallPlacementPointsJson: ['{}'],
      overallPlacementPoints,
      rosterRulesJson: ['{}'],
      bracketRulesJson: ['{}'],
      standingsRulesJson: ['{}'],
      standingsWinPoints: [3, Validators.required],
      standingsDrawPoints: [1, Validators.required],
      standingsLossPoints: [0, Validators.required],
      standingsByePoints: [3, Validators.required],
      doubleRoundRobin: [false],
      groupCount: [2, [Validators.required, Validators.min(2), Validators.max(128)]],
      qualifiersPerGroup: [2, [Validators.required, Validators.min(1), Validators.max(128)]],
      swissMaximumRounds: [5, [Validators.required, Validators.min(1), Validators.max(128)]],
      registrationFormId: [''],
    }),
    team: fb.nonNullable.group({
      id: [''],
      name: ['', Validators.required],
      institution: [''],
      status: ['DRAFT'],
    }),
    registration: fb.nonNullable.group({
      teamId: ['', Validators.required],
      categoryId: ['', Validators.required],
      seed: [0],
      formAnswersJson: ['[]'],
    }),
    match: fb.nonNullable.group(
      {
        id: [''],
        categoryId: ['', Validators.required],
        name: ['Partida'],
        startDate: ['', Validators.required],
        endDate: ['', Validators.required],
        stageId: [''],
        venueId: [''],
        homeRegistrationId: [''],
        awayRegistrationId: [''],
        roundNumber: [1],
        bracketPosition: [1],
        groupKey: [''],
        state: ['SCHEDULED'],
        notes: ['', Validators.maxLength(2_000)],
        livestreamProvider: [''],
        livestreamUrl: ['', Validators.pattern(/^https:\/\/.+/i)],
      },
      { validators: livestreamValidator },
    ),
    representative: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
    }),
    member: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
    }),
    official: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
      role: ['REFEREE'],
      scope: ['MATCH'],
    }),
    scoreEntry: fb.nonNullable.group({
      teamId: ['', Validators.required],
      source: ['MANUAL'],
      points: [0],
      reason: ['', Validators.required],
    }),
    venue: fb.nonNullable.group({
      id: [''],
      placePresetId: ['', Validators.required],
      name: ['', Validators.required],
      courtLabel: [''],
      capacity: [0],
      notes: [''],
      parentVenueId: [''],
    }),
    bracket: fb.nonNullable.group({
      randomizeUnseeded: [true],
      randomSeed: [''],
      replaceExistingDraft: [false],
    }),
  };
}

export function createPlacementPointForm(fb: FormBuilder, position: number, points = 0) {
  return fb.group({
    position: fb.nonNullable.control(position, [Validators.required, Validators.min(1), Validators.max(100)]),
    points: fb.nonNullable.control(points, [Validators.required, Validators.min(0), Validators.max(1_000_000)]),
  });
}
