import { FormBuilder, Validators } from '@angular/forms';
import {
  jsonObjectValidator,
  livestreamValidator,
  scoreRulesValidator,
} from './sports-workspace-form.utils';

export function createSportsWorkspaceForms(fb: FormBuilder) {
  return {
    tournamentLookup: fb.nonNullable.group({ tournamentId: [''] }),
    tournament: fb.nonNullable.group({
      status: ['DRAFT'],
      scoringMode: ['PER_SPORT'],
      selfSubscriptionEnabled: [false],
      selfSubscriptionAllowNoTeam: [false],
      selfSubscriptionAllowNoCategory: [false],
      allowPlayerMultipleTeams: [false],
    }),
    category: fb.nonNullable.group({
      id: [''],
      name: ['', Validators.required],
      emoji: ['⚽', Validators.required],
      sport: ['SOCCER'],
      customSportName: [''],
      division: [''],
      format: ['SINGLE_ELIMINATION'],
      status: ['DRAFT'],
      registrationStartDate: [''],
      registrationEndDate: [''],
      minimumRosterSize: [0],
      maximumRosterSize: [0],
      maximumCaptains: [0],
      maximumCoaches: [0],
      allowPlayerMultipleTeams: [false],
      periodsEnabled: [false],
      maximumPeriods: [0],
      periodLabel: ['Tempo'],
      timerPreset: ['SOCCER'],
      timerOverallEnabled: [true],
      timerPeriodEnabled: [true],
      timerPeriodDurationMinutes: [45, [Validators.min(0), Validators.max(1440)]],
      timerAllowOvertime: [true],
      timerPeriodStartOffsetsMinutes: [
        '0, 45',
        Validators.pattern(/^\s*\d+(?:\.\d+)?(?:\s*,\s*\d+(?:\.\d+)?)*\s*$/),
      ],
      rulesText: [''],
      scoreRulesJson: ['{}', scoreRulesValidator],
      rosterRulesJson: ['{}', jsonObjectValidator],
      bracketRulesJson: ['{}', jsonObjectValidator],
      standingsRulesJson: ['{}', jsonObjectValidator],
      registrationFormId: [''],
    }),
    team: fb.nonNullable.group({
      id: [''],
      name: ['', Validators.required],
      institution: [''],
      status: ['DRAFT'],
    }),
    registration: fb.nonNullable.group({
      teamId: ['', Validators.required],
      categoryId: ['', Validators.required],
      seed: [0],
      formAnswersJson: ['{}', jsonObjectValidator],
    }),
    match: fb.nonNullable.group(
      {
        id: [''],
        categoryId: ['', Validators.required],
        name: ['Partida'],
        startDate: ['', Validators.required],
        endDate: ['', Validators.required],
        stageId: [''],
        venueId: [''],
        homeRegistrationId: [''],
        awayRegistrationId: [''],
        roundNumber: [1],
        bracketPosition: [1],
        groupKey: [''],
        state: ['SCHEDULED'],
        notes: ['', Validators.maxLength(2_000)],
        livestreamProvider: [''],
        livestreamUrl: ['', Validators.pattern(/^https:\/\/.+/i)],
      },
      { validators: livestreamValidator },
    ),
    representative: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
    }),
    member: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
    }),
    categoryRole: fb.nonNullable.group({
      registrationId: ['', Validators.required],
      teamMemberId: ['', Validators.required],
      role: ['PLAYER'],
    }),
    official: fb.nonNullable.group({
      personQuery: ['', Validators.required],
      personId: ['', Validators.required],
      role: ['REFEREE'],
      scope: ['MATCH'],
    }),
    scoreEntry: fb.nonNullable.group({
      teamId: ['', Validators.required],
      source: ['MANUAL'],
      points: [0],
      reason: ['', Validators.required],
    }),
    venue: fb.nonNullable.group({
      id: [''],
      placePresetId: ['', Validators.required],
      name: ['', Validators.required],
      courtLabel: [''],
      capacity: [0],
      notes: [''],
      parentVenueId: [''],
    }),
    bracket: fb.nonNullable.group({
      randomizeUnseeded: [true],
      randomSeed: [''],
      replaceExistingDraft: [false],
    }),
  };
}
