// Generated by tools/generate-audience-relations.mjs. Do not edit by hand.
export const AUDIENCE_RELATIONS = {
  "AttendanceReviewFlag": [],
  "AttendanceScanAttemptCounter": [],
  "EventAttendance": [
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventAttendanceCollector": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "OfflineEventAttendanceSubmission": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "EventAudienceInvitation": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventGroupAudienceInvitation": [
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "MajorEventAudienceInvitation": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "AuditLogEntry": [],
  "LgpdStorageCleanupOutbox": [],
  "CertificateTemplate": [
    {
      "name": "certificateConfigs",
      "type": "CertificateConfig",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "certificates",
      "type": "Certificate",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "CertificateFolder": [
    {
      "name": "certificateConfigs",
      "type": "CertificateConfig",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "CertificateConfig": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "folder",
      "type": "CertificateFolder",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "certificateTemplate",
      "type": "CertificateTemplate",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "certificates",
      "type": "Certificate",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "Certificate": [
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "config",
      "type": "CertificateConfig",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "certificateTemplate",
      "type": "CertificateTemplate",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "notificationOutbox",
      "type": "CertificateNotificationOutbox",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "CertificateNotificationOutbox": [
    {
      "name": "certificate",
      "type": "Certificate",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventGroup": [
    {
      "name": "audienceInvitations",
      "type": "EventGroupAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "events",
      "type": "Event",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "subscriptions",
      "type": "EventGroupSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "interests",
      "type": "EventInterest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventManagerRoleAssignmentScopes",
      "type": "EventManagerRoleAssignmentScope",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsCategory",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "certificateConfigs",
      "type": "CertificateConfig",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "Event": [
    {
      "name": "audienceInvitations",
      "type": "EventAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "drafts",
      "type": "EventDraft",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "ownedForms",
      "type": "EventForm",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "formLinks",
      "type": "EventFormLink",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "formResponses",
      "type": "EventFormResponse",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "attendances",
      "type": "EventAttendance",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "attendanceCollectors",
      "type": "EventAttendanceCollector",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "offlineAttendanceSubmissions",
      "type": "OfflineEventAttendanceSubmission",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "lecturers",
      "type": "EventLecturer",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventManagerRoleAssignmentScopes",
      "type": "EventManagerRoleAssignmentScope",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "subscriptions",
      "type": "EventSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "interests",
      "type": "EventInterest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "majorEventSelections",
      "type": "MajorEventSubscriptionEventSelection",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsMatch",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "prizeDraws",
      "type": "PrizeDraw",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "certificateConfigs",
      "type": "CertificateConfig",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventDraft": [
    {
      "name": "sourceEvent",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "PlacePreset": [
    {
      "name": "sportsVenues",
      "type": "SportsVenue",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventLecturer": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "PublicationPreview": [],
  "ExternalImportRecord": [],
  "EventForm": [
    {
      "name": "ownerEvent",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "ownerMajorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "links",
      "type": "EventFormLink",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "responses",
      "type": "EventFormResponse",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "drafts",
      "type": "EventFormDraft",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "images",
      "type": "EventFormImage",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsCategoryRegistrationForms",
      "type": "SportsCategory",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventFormImage": [
    {
      "name": "form",
      "type": "EventForm",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "EventFormLink": [
    {
      "name": "form",
      "type": "EventForm",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "responses",
      "type": "EventFormResponse",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "priceTiers",
      "type": "EventFormLinkPriceTier",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventFormLinkPriceTier": [
    {
      "name": "link",
      "type": "EventFormLink",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "priceTier",
      "type": "PriceTier",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventFormResponse": [
    {
      "name": "form",
      "type": "EventForm",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "link",
      "type": "EventFormLink",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventFormDraft": [
    {
      "name": "sourceForm",
      "type": "EventForm",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventInterest": [
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "LecturerProfile": [
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "MajorEvent": [
    {
      "name": "audienceInvitations",
      "type": "MajorEventAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "events",
      "type": "Event",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventGroups",
      "type": "EventGroup",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventManagerRoleAssignmentScopes",
      "type": "EventManagerRoleAssignmentScope",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "ownedForms",
      "type": "EventForm",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "formLinks",
      "type": "EventFormLink",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "formResponses",
      "type": "EventFormResponse",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "subscriptions",
      "type": "MajorEventSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "interests",
      "type": "EventInterest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsTournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "prizeDraws",
      "type": "PrizeDraw",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "paymentInfo",
      "type": "PaymentInfo",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "majorEventPrices",
      "type": "MajorEventPrice",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "certificateConfigs",
      "type": "CertificateConfig",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PaymentInfo": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "MajorEventReceipt": [
    {
      "name": "subscription",
      "type": "MajorEventSubscription",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "validationActions",
      "type": "MajorEventReceiptValidationAction",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "MajorEventReceiptValidationAction": [
    {
      "name": "subscription",
      "type": "MajorEventSubscription",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "receipt",
      "type": "MajorEventReceipt",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "MajorEventPrice": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "tiers",
      "type": "PriceTier",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PriceTier": [
    {
      "name": "price",
      "type": "MajorEventPrice",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "eventFormLinks",
      "type": "EventFormLinkPriceTier",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PeopleMergeOperation": [
    {
      "name": "targetPerson",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "sourcePerson",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "mergeCandidate",
      "type": "MergeCandidate",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "externalAccountMergeOperations",
      "type": "ExternalAccountMergeOperation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "MergeCandidate": [
    {
      "name": "personA",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "personB",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "mergeOperations",
      "type": "PeopleMergeOperation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "People": [
    {
      "name": "eventAudienceInvitations",
      "type": "EventAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventGroupAudienceInvitations",
      "type": "EventGroupAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "majorEventAudienceInvitations",
      "type": "MajorEventAudienceInvitation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "user",
      "type": "User",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "attendances",
      "type": "EventAttendance",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "lectures",
      "type": "EventLecturer",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "attendanceCollectorFor",
      "type": "EventAttendanceCollector",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "offlineAttendanceSubmissions",
      "type": "OfflineEventAttendanceSubmission",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventSubscriptions",
      "type": "EventSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventInterests",
      "type": "EventInterest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventGroupSubscriptions",
      "type": "EventGroupSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "majorEventSubscriptions",
      "type": "MajorEventSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventFormResponses",
      "type": "EventFormResponse",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "lecturerProfile",
      "type": "LecturerProfile",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "eventManagerRoleAssignments",
      "type": "EventManagerRoleAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "eventManagerGroupMemberships",
      "type": "EventManagerPermissionGroupMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsTournamentParticipants",
      "type": "SportsTournamentParticipant",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsTeamRepresentatives",
      "type": "SportsTeamRepresentative",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsSubmittedTeamChanges",
      "type": "SportsTeamChangeRequest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsResolvedIdentityClaims",
      "type": "SportsIdentityClaim",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsOfficialAssignments",
      "type": "SportsOfficialAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsMatchActions",
      "type": "SportsMatchAction",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsPlayerApplications",
      "type": "SportsPlayerApplication",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawManualEntries",
      "type": "PrizeDrawManualEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawWeightOverrides",
      "type": "PrizeDrawWeightOverride",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawExclusions",
      "type": "PrizeDrawExcludedPerson",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawFrozenEntries",
      "type": "PrizeDrawFrozenEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawSpinEntries",
      "type": "PrizeDrawSpinEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "prizeDrawWins",
      "type": "PrizeDrawSpin",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "mergedInto",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "mergedFrom",
      "type": "People",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "mergeCandidatesA",
      "type": "MergeCandidate",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "mergeCandidatesB",
      "type": "MergeCandidate",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "mergeOperationsAsTarget",
      "type": "PeopleMergeOperation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "mergeOperationsAsSource",
      "type": "PeopleMergeOperation",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "certificates",
      "type": "Certificate",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventManagerRole": [
    {
      "name": "permissions",
      "type": "EventManagerRolePermission",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "assignments",
      "type": "EventManagerRoleAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "parentLinks",
      "type": "EventManagerRoleInheritance",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "childLinks",
      "type": "EventManagerRoleInheritance",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventManagerRolePermission": [
    {
      "name": "role",
      "type": "EventManagerRole",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventManagerRoleInheritance": [
    {
      "name": "childRole",
      "type": "EventManagerRole",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "parentRole",
      "type": "EventManagerRole",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventManagerRoleAssignment": [
    {
      "name": "role",
      "type": "EventManagerRole",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "group",
      "type": "EventManagerPermissionGroup",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "scopes",
      "type": "EventManagerRoleAssignmentScope",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventManagerRoleAssignmentScope": [
    {
      "name": "assignment",
      "type": "EventManagerRoleAssignment",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "EventManagerPermissionGroup": [
    {
      "name": "members",
      "type": "EventManagerPermissionGroupMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "assignments",
      "type": "EventManagerRoleAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "EventManagerPermissionGroupMember": [
    {
      "name": "group",
      "type": "EventManagerPermissionGroup",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "PrizeDraw": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "plannedSpins",
      "type": "PrizeDrawPlannedSpin",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "manualEntries",
      "type": "PrizeDrawManualEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "weightOverrides",
      "type": "PrizeDrawWeightOverride",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "excludedPeople",
      "type": "PrizeDrawExcludedPerson",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "frozenEntries",
      "type": "PrizeDrawFrozenEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "spins",
      "type": "PrizeDrawSpin",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PrizeDrawPlannedSpin": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "spins",
      "type": "PrizeDrawSpin",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PrizeDrawManualEntry": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "PrizeDrawWeightOverride": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "PrizeDrawExcludedPerson": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "PrizeDrawFrozenEntry": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "PrizeDrawSpin": [
    {
      "name": "draw",
      "type": "PrizeDraw",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "plannedSpin",
      "type": "PrizeDrawPlannedSpin",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "winnerPerson",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "entries",
      "type": "PrizeDrawSpinEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "PrizeDrawSpinEntry": [
    {
      "name": "spin",
      "type": "PrizeDrawSpin",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "SportsTournament": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "categories",
      "type": "SportsCategory",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "teams",
      "type": "SportsTeam",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "venues",
      "type": "SportsVenue",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "participants",
      "type": "SportsTournamentParticipant",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "officials",
      "type": "SportsOfficialAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "playerApplications",
      "type": "SportsPlayerApplication",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "scoreEntries",
      "type": "SportsTournamentScoreEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsCategory": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "registrationForm",
      "type": "EventForm",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "registrations",
      "type": "SportsRegistration",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "memberAssignments",
      "type": "SportsRegistrationMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "stages",
      "type": "SportsStage",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "matches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "officialAssignments",
      "type": "SportsOfficialAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "applicationChoices",
      "type": "SportsPlayerApplicationCategory",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "scoreEntries",
      "type": "SportsTournamentScoreEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsCategoryPlacements",
      "type": "SportsCategoryPlacement",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsTeam": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "members",
      "type": "SportsTeamMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "representatives",
      "type": "SportsTeamRepresentative",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "registrations",
      "type": "SportsRegistration",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "changeRequests",
      "type": "SportsTeamChangeRequest",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "scoreEntries",
      "type": "SportsTournamentScoreEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "applications",
      "type": "SportsPlayerApplication",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsTournamentParticipant": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "majorEventSubscription",
      "type": "MajorEventSubscription",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "teamMemberships",
      "type": "SportsTeamMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsTeamMember": [
    {
      "name": "team",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "participant",
      "type": "SportsTournamentParticipant",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "categoryAssignments",
      "type": "SportsRegistrationMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsTeamRepresentative": [
    {
      "name": "team",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "SportsRegistration": [
    {
      "name": "team",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "members",
      "type": "SportsRegistrationMember",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "homeMatches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "awayMatches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "wonMatches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "lostMatches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "rosters",
      "type": "SportsMatchRoster",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "categoryPlacements",
      "type": "SportsCategoryPlacement",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsStandings",
      "type": "SportsStanding",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsRegistrationMember": [
    {
      "name": "registration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "teamMember",
      "type": "SportsTeamMember",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "rosterEntries",
      "type": "SportsMatchRosterEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsTeamChangeRequest": [
    {
      "name": "team",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "submittedByPerson",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "identityClaims",
      "type": "SportsIdentityClaim",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsIdentityClaim": [
    {
      "name": "request",
      "type": "SportsTeamChangeRequest",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "resolvedPerson",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "SportsVenue": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "placePreset",
      "type": "PlacePreset",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "parentVenue",
      "type": "SportsVenue",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "childVenues",
      "type": "SportsVenue",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "matches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsStage": [
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "matches",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "standings",
      "type": "SportsStanding",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsMatch": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "stage",
      "type": "SportsStage",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "venue",
      "type": "SportsVenue",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "homeRegistration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "awayRegistration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "winnerRegistration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "loserRegistration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "winnerAdvancesTo",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "winnerSources",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "loserAdvancesTo",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "loserSources",
      "type": "SportsMatch",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "replayOfMatch",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "replayMatch",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "rosters",
      "type": "SportsMatchRoster",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "actions",
      "type": "SportsMatchAction",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "officialAssignments",
      "type": "SportsOfficialAssignment",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sourceScoreEntries",
      "type": "SportsTournamentScoreEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "categoryPlacements",
      "type": "SportsCategoryPlacement",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsMatchRoster": [
    {
      "name": "match",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "registration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "copiedFromRoster",
      "type": "SportsMatchRoster",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "copiedToRosters",
      "type": "SportsMatchRoster",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "entries",
      "type": "SportsMatchRosterEntry",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsMatchRosterEntry": [
    {
      "name": "roster",
      "type": "SportsMatchRoster",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "registrationMember",
      "type": "SportsRegistrationMember",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "scoredActions",
      "type": "SportsMatchAction",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsOfficialAssignment": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "match",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "SportsMatchAction": [
    {
      "name": "match",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "scorerRosterEntry",
      "type": "SportsMatchRosterEntry",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "actorPerson",
      "type": "People",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "SportsStanding": [
    {
      "name": "stage",
      "type": "SportsStage",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "registration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "SportsCategoryPlacement": [
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "registration",
      "type": "SportsRegistration",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "sourceMatch",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "SportsTournamentScoreEntry": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "team",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "sourceMatch",
      "type": "SportsMatch",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "SportsPlayerApplication": [
    {
      "name": "tournament",
      "type": "SportsTournament",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "applicantPerson",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "requestedTeam",
      "type": "SportsTeam",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    },
    {
      "name": "categoryChoices",
      "type": "SportsPlayerApplicationCategory",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "SportsPlayerApplicationCategory": [
    {
      "name": "application",
      "type": "SportsPlayerApplication",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "category",
      "type": "SportsCategory",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "EventSubscription": [
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "eventGroupSubscription",
      "type": "EventGroupSubscription",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ],
  "EventGroupSubscription": [
    {
      "name": "eventGroup",
      "type": "EventGroup",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "eventSubscriptions",
      "type": "EventSubscription",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "MajorEventSubscription": [
    {
      "name": "majorEvent",
      "type": "MajorEvent",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "person",
      "type": "People",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "selectedEvents",
      "type": "MajorEventSubscriptionEventSelection",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "receipts",
      "type": "MajorEventReceipt",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "validationActions",
      "type": "MajorEventReceiptValidationAction",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "sportsTournamentParticipants",
      "type": "SportsTournamentParticipant",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    }
  ],
  "MajorEventSubscriptionEventSelection": [
    {
      "name": "subscription",
      "type": "MajorEventSubscription",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    },
    {
      "name": "event",
      "type": "Event",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "User": [
    {
      "name": "people",
      "type": "People",
      "isList": true,
      "isRequired": true,
      "ownsRelation": false
    },
    {
      "name": "calendarFeedSettings",
      "type": "UserCalendarFeedSettings",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    },
    {
      "name": "adminCalendarFeedSettings",
      "type": "UserAdminCalendarFeedSettings",
      "isList": false,
      "isRequired": false,
      "ownsRelation": false
    }
  ],
  "UserCalendarFeedSettings": [
    {
      "name": "user",
      "type": "User",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "UserAdminCalendarFeedSettings": [
    {
      "name": "user",
      "type": "User",
      "isList": false,
      "isRequired": true,
      "ownsRelation": true
    }
  ],
  "SuperAdminCalendarFeedSettings": [],
  "AccountUserMerge": [],
  "ExternalAccountMergeOperation": [
    {
      "name": "peopleMergeOperation",
      "type": "PeopleMergeOperation",
      "isList": false,
      "isRequired": false,
      "ownsRelation": true
    }
  ]
} as const;
