import { Permission, type PermissionRequirement } from './permission-types';

export const EVENT_MANAGER_PERMISSION_CATALOG = [
  Permission.Certificate.Read,
  Permission.Certificate.Issue,
  Permission.Certificate.Reissue,
  Permission.Certificate.Delete,
  Permission.CertificateConfig.Read,
  Permission.CertificateConfig.Create,
  Permission.CertificateConfig.Update,
  Permission.CertificateConfig.Delete,
  Permission.Event.Read,
  Permission.Event.Create,
  Permission.Event.Update,
  Permission.Event.Delete,
  Permission.EventAttendance.Read,
  Permission.EventAttendance.Collect,
  Permission.EventAttendance.Import,
  Permission.EventAttendance.Update,
  Permission.EventAttendance.Delete,
  Permission.EventAttendanceCollector.Read,
  Permission.EventAttendanceCollector.Create,
  Permission.EventAttendanceCollector.Delete,
  Permission.EventGroup.Read,
  Permission.EventGroup.Create,
  Permission.EventGroup.Update,
  Permission.EventGroup.Delete,
  Permission.EventLecturer.Read,
  Permission.EventLecturer.Create,
  Permission.EventLecturer.Update,
  Permission.EventLecturer.Delete,
  Permission.EventForm.Read,
  Permission.EventForm.Create,
  Permission.EventForm.Update,
  Permission.EventForm.Delete,
  Permission.EventForm.Publish,
  Permission.EventForm.Results,
  Permission.EventForm.Export,
  Permission.Frozen.Update,
  Permission.Frozen.Delete,
  Permission.MajorEvent.Read,
  Permission.MajorEvent.Create,
  Permission.MajorEvent.Update,
  Permission.MajorEvent.Delete,
  Permission.MergeCandidate.Read,
  Permission.MergeCandidate.Create,
  Permission.MergeCandidate.Update,
  Permission.MergeCandidate.Scan,
  Permission.MergeCandidate.Merge,
  Permission.MergeCandidate.Undo,
  Permission.MergeCandidate.Delete,
  Permission.Person.Read,
  Permission.Person.Create,
  Permission.Person.Update,
  Permission.Person.Delete,
  Permission.PermissionGrant.Read,
  Permission.PermissionGrant.Create,
  Permission.PermissionGrant.Update,
  Permission.PermissionGrant.Delete,
  Permission.PlacePreset.Read,
  Permission.PlacePreset.Create,
  Permission.PlacePreset.Update,
  Permission.PlacePreset.Merge,
  Permission.PlacePreset.Delete,
  Permission.Receipt.Read,
  Permission.Receipt.Approve,
  Permission.Receipt.Reject,
  Permission.Receipt.Undo,
  Permission.Subscription.Read,
  Permission.Subscription.Create,
  Permission.Subscription.Update,
  Permission.Subscription.Import,
  Permission.Subscription.Delete,
  Permission.User.Read,
] as const satisfies PermissionRequirement;

export const EVENT_MANAGER_PERMISSION_SET = new Set<Permission>(EVENT_MANAGER_PERMISSION_CATALOG);

export const EVENT_MANAGER_GLOBAL_ONLY_GRANT_PERMISSIONS = [
  Permission.MergeCandidate.Read,
  Permission.MergeCandidate.Create,
  Permission.MergeCandidate.Update,
  Permission.MergeCandidate.Scan,
  Permission.MergeCandidate.Merge,
  Permission.MergeCandidate.Undo,
  Permission.MergeCandidate.Delete,
  Permission.Person.Read,
  Permission.Person.Create,
  Permission.Person.Update,
  Permission.Person.Delete,
  Permission.PermissionGrant.Read,
  Permission.PermissionGrant.Create,
  Permission.PermissionGrant.Update,
  Permission.PermissionGrant.Delete,
  Permission.PlacePreset.Read,
  Permission.PlacePreset.Create,
  Permission.PlacePreset.Update,
  Permission.PlacePreset.Merge,
  Permission.PlacePreset.Delete,
  Permission.User.Read,
] as const satisfies PermissionRequirement;

export const EVENT_MANAGER_GLOBAL_ONLY_GRANT_PERMISSION_SET = new Set<Permission>(
  EVENT_MANAGER_GLOBAL_ONLY_GRANT_PERMISSIONS,
);

export function requiresGlobalPermissionGrantScope(permission: Permission): boolean {
  return EVENT_MANAGER_GLOBAL_ONLY_GRANT_PERMISSION_SET.has(permission);
}
