import { BadRequestException, Controller, HttpCode, Param, Post, RawBodyRequest, Req, UseGuards } from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiBody,
  ApiConsumes,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import type { Request } from 'express';

import { AnalyticsService } from './analytics.service';
import { SENTRY_TUNNEL_TARGETS } from './analytics.config';
import { Public } from '../auth/decorators/public.decorator';
import { RateLimit } from '../rate-limit/rate-limit.decorator';
import { RateLimitGuard } from '../rate-limit/rate-limit.guard';
import { RATE_LIMIT_POLICIES } from '../rate-limit/rate-limit.policies';

@ApiTags('Analytics')
@Controller('a')
export class AnalyticsController {
  constructor(private readonly analyticsService: AnalyticsService) {}

  @Post('glitchtip/:project')
  @Public()
  @UseGuards(RateLimitGuard)
  @RateLimit(RATE_LIMIT_POLICIES.publicAnalytics, [{ source: 'params', path: 'project' }])
  @HttpCode(200)
  @ApiOperation({
    summary: 'Forward Sentry envelope events',
    description:
      'Receives Sentry envelope payloads from frontend SDK tunnel requests and forwards them to the configured GlitchTip project. ' +
      'This endpoint is intended to avoid ad blockers blocking direct browser requests to Sentry envelope URLs.',
  })
  @ApiParam({
    name: 'project',
    description: 'Configured monitoring project key. Must match one of the keys in SENTRY_TUNNEL_TARGETS.',
    enum: Object.keys(SENTRY_TUNNEL_TARGETS),
    example: Object.keys(SENTRY_TUNNEL_TARGETS)[0],
  })
  @ApiConsumes('application/x-sentry-envelope', 'text/plain')
  @ApiBody({
    required: true,
    description:
      'Raw Sentry envelope payload generated by the Sentry JavaScript SDK. The body must be forwarded unchanged.',
    schema: {
      type: 'string',
      format: 'binary',
      example:
        '{"event_id":"...","dsn":"https://PUBLIC_KEY@glitchtip.cacic.com.br/ID"}\n{"type":"event"}\n{"message":"Example error"}',
    },
  })
  @ApiResponse({
    status: 200,
    description: 'Envelope accepted by the backend tunnel and forwarded to GlitchTip.',
  })
  @ApiBadRequestResponse({
    description: 'Unknown monitoring project or malformed request.',
  })
  async tunnel(@Param('project') project: string, @Req() req: RawBodyRequest<Request>): Promise<void> {
    if (!(project in SENTRY_TUNNEL_TARGETS)) {
      throw new BadRequestException('Unknown monitoring project');
    }

    await this.analyticsService.forwardEnvelope(project, req);
  }
}
